### PR TITLE
JsonPost example code minimizing

### PR DESCRIPTION
**Pull request by muturgan**
JsonPost example code minimizing

### CODE REVIEW

**Comment by muturgan** [comment]
well, i have just change an example code, and then the check have failed?

**Comment by slavaGanzin** [comment]
How this project attracts so much pretentious noobs? This is not even named react-*something*...

**Comment by muturgan** [comment]
> How this project attracts so much pretentious noobs? This is not even named react-_something_...

it looks like this project is better then react!

**Comment by muturgan** [comment]
> How this project attracts so much pretentious noobs? This is not even named react-_something_...

btw i hate react

**Pull request closed without merging**
