### PR TITLE
Fix bug on Linux

### PR DESCRIPTION
**Pull request by hans00**
string.c_str() may auto GC on Linux.

### CODE REVIEW

**Comment by alexhultman** [comment]
There is no garbage collector in C. This PR introduce memory leaks and doesn't fix anything.

**Comment by hans00** [comment]
I found the problem in my case.
When options is from external, the string will GC by Node.js.
image

**Comment by hans00** [comment]
And clone Object cannot help to solve this problem.
image
image

Only direct pass string can solve.
image

**Comment by alexhultman** [comment]
I don't know what you're on about. What version are you using and what fails?

What you describe is not how things work, there is no GC involved at all.

**Comment by hans00** [comment]
My Node.js version is v12.13.1

I tracked the variable `options.cert_file_name`, it will be garbage pointer before construction.
image
image

**Comment by alexhultman** [comment]
The issue is fixed: https://github.com/uNetworking/uWebSockets.js/commit/e45994a9d024aa324a984e06ea3328c1dea16c76

You need to have a look at how C++ works before making PRs; this has nothing to do with garbage collection or Node.js - it was a scoping mistake where you would want to move the std::strings up one scope.

The PR you posted is a "fix" that introduce one memory leak for every option; that's not acceptable.

**Comment by hans00** [comment]
Thanks.

May be I need to review C++ characteristic, I'm been a long time not write C++.

**Comment by alexhultman** [comment]
Thanks for pointing at the issue

**Pull request closed without merging**
