### PR TITLE
Add file upload example

### PR DESCRIPTION
**Pull request by krm35**

### CODE REVIEW

**Comment by uNetworkingAB** [comment]
const {fileName} = querystring.parse(req.getQuery());

We have res.getQuery("filename") and we also have MultipartParser built-in.

**Comment by IonelLupu** [comment]
@krm35 @uNetworkingAB  I debugged big file upload for hours and I noticed you have to copy the chunk, the write it on disk (or whatever stream). 

For example, this `.slice(0)` from this line `writeStream.write(Buffer.from(chunk.slice(0)));` is super important. Otherwise, it won't write anything to the stream.

What is the explanation?

**Comment by krm35** [comment]
Needs to slice to make a deep copy of the chunk otherwise there is a reference problem

**Comment by uNetworkingAB** [comment]
It's always a good idea to read the documentation https://unetworking.github.io/uWebSockets.js/generated/interfaces/HttpResponse.html#onData

**Pull request closed without merging**
