### PR TITLE
Match Existing Code As Much as Possible

### PR DESCRIPTION
**Pull request by coder456**
Need a generic `readBody` function that can be re-used, do small refactor, match existing styling, change as little code as possible
<hr>

```
/* Simple example of getting JSON from a POST */

const uWS = require('../dist/uws.js');
const port = 9001;

const app = uWS./*SSL*/App({
  key_file_name: 'misc/key.pem',
  cert_file_name: 'misc/cert.pem',
  passphrase: '1234'
}).post('/*', (res, req) => {

  /* onAborted needs to be set if doing anything async like reading body */
  res.onAborted(() => res.aborted = true);

  /* Note that you cannot read from req after returning from here */
  let url = req.getUrl();

  /* Read the body until done */
  readBody(res, (body) => {

    /* body text as string */
    console.log('body text:', body.toString());

    /* parse json */
    try { var obj = JSON.parse(body); }
    catch(e) { console.log('json parse error'); }

    console.log('Posted to ' + url + ': ');
    console.log(obj);

    /* if response was aborted can't use it */
    if (res.aborted) return;

    if (obj) {
      res.end('Thanks for this json!');
    } else {
      res.writeStatus('400').end('invalid json');
    }
  });

}).listen(port, (token) => {
  if (token) {
    console.log('Listening to port ' + port);
  } else {
    console.log('Failed to listen to port ' + port);
  }
});

/* Helper function for reading a posted body */
function readBody(res, cb) {
  let body;
  res.onData((arrayBuffer, isLast) => {
    const chunk = Buffer.from(arrayBuffer);
    body = body ? Buffer.concat([body, chunk]) : isLast ? chunk : Buffer.from(chunk);
    if (isLast) cb(body);
  });
}
```

### CODE REVIEW

**Comment by alexhultman** [comment]
You are trying to simplify something that shouldn't be simple. It's not what we do here.

If anything, improve the streaming APIs - wrapping the streaming APIs into a simple-to-use in-memory buffering function is not a goal here. It's simplifying the wrong solution.

**Comment by coder456** [comment]
Hmm I am really losing confidence in your ability to manage a library. I am simply doing what every other person will need to do if they want to parse the Body, they will need to dissect your Json Post mess and re-code that into what is in this PR. Apparently you are trying to make it difficult for people on purpose which is strange. This code is exactly the same thing as you Json Parse except this is usable and readable.

**Comment by alexhultman** [comment]
#183 #184 #182 #185

> I code javascript full time for many years get paid well for my job, I am assuming you dont have much javascript experience, who codes with spaces for indentation? strange stuff, this is supposed to be as simple as possible

> This is how JavaScript is supposed to be written, you don't seem interested in the success of your own library if you dont make available a simple readBody function

> Hmm I am really losing confidence in your ability to manage a library. I am simply doing what every other person will need to do if they want to parse the Body, they will need to dissect your Json Post mess and re-code that into what is in this PR. Apparently you are trying to make it difficult for people on purpose which is strange. This code is exactly the same thing as you Json Parse except this is usable and readable.

Okay, so go make your own project.

You're banned from here.

**Comment by coder567** [comment]
Yes get your panties in a bunch and ban someone who is only trying to help your other users congratz good work

**Comment by alexhultman** [comment]
Good luck with your full time job, I hope your colleagues are nice to you despite the arrogance and narcissistic traits of yours. It is perfectly fine being a little arrogant as long as you make up for it with other qualities. Best of luck.

**Pull request closed without merging**
