### PR TITLE
update docs, add defaults

### PR DESCRIPTION
**Pull request by hst-m**

### CODE REVIEW

**Comment by alexhultman** [comment]
Defaults are not the same in the wrapper as in the native lib. I think we default to 0 everywhere in the wrapper.

**Comment by hst-m** [comment]
I am no c expert but test shows 120 sec timeout default

**Comment by alexhultman** [comment]
I'm not sure, but I think for instance idleTimeout will be default to 0 in the wrapper

**Comment by hst-m** [comment]
tested again with v18.11 and v18.12, 120 second default idleTimeout, assuming the other defaults also apply

**Pull request merged**
