### PR TITLE
Update build.c

### PR DESCRIPTION
**Pull request by murataka**
add freebsd support

### CODE REVIEW

**Comment by alexhultman** [comment]
This PR is not (entirely) correct. You have duplicate entries for Nodejs 14 and you do not build for ARM64. But FreeBSD is not exactly a supported platform - it **could** be added if more users need it, but we also have to consider the people who get mad for shipping too many binaries.

**Comment by murataka** [comment]
> This PR is not (entirely) correct. You have duplicate entries for Nodejs 14 and you do not build for ARM64. But FreeBSD is not exactly a supported platform - it **could** be added if more users need it, but we also have to consider the people who get mad for shipping too many binaries.

I have tested it and seems to work. As my platform is not arm , and this would be not tested , i did not copy the build line. I am using nodejs 14.5 in production, so do not update frequently. This is why i needed to add that. Also , some other versions will not work and needs to be compiled already ( 14.1 , 14.2 etc. )

The binaries will not be a problem to compile on unix or linux , a command to build the needed binary can be added to JS wrapper , say windows binary may come precompiled , for other platforms, the JS module would print how to comile ( please run COMMAND TO BUILD for installation to complete,  ) or build.c can come with old binaries commented out .

**Comment by alexhultman** [comment]
14.5 is the same as 14.x. They are both ABI 83, so you have indeed added a duplicate.

We do arm64, amd64 so like I said you're missing arm64.

But like I also said FreeBSD is not a priority right now

**Comment by murataka** [comment]
> 14.5 is the same as 14.x. They are both ABI 83, so you have indeed added a duplicate.
> 
> We do arm64, amd64 so like I said you're missing arm64.
> 
> But like I also said FreeBSD is not a priority right now

its ok, uws wanted that exact version, that is why 14.5 ...

**Comment by alexhultman** [comment]
Closing as you repeatedly fail to listen to what I'm saying

**Comment by murataka** [comment]
> But like I also said FreeBSD is not a priority right now

Also,there is also much work to do on uws.js . 

> Closing as you repeatedly fail to listen to what I'm saying

I understood all , and its ok.

**Pull request closed without merging**
