### PR TITLE
Build for arm 32-bit

### PR DESCRIPTION
**Pull request by adonespitogo**

### CODE REVIEW

**Comment by adonespitogo** [comment]
Tested on raspberry pi 3 Model B.

**Comment by uNetworkingAB** [comment]
This is 100% unsupported but looks like it won't harm to have it there

**Comment by adonespitogo** [comment]
@uNetworkingAB Can you elaborate why this is not supported? And if it is not supported, is it still possible to add a binary for 32-bit arm?

I really needed this to work on RPI and other SBC's for our project.

**Comment by uNetworkingAB** [comment]
What I mean is, none of the 32-bit platforms are tested. I haven't had a 32-bit system in many years and never will.

**Comment by uNetworkingAB** [comment]
Even my Raspberry Pi 4 is 64-bit

**Comment by adonespitogo** [comment]
I can do the testing for 32-bit systems if you're open to it. Actually we are a small company and our products run mostly on SBCs and microprocessors. We will definitely allocate some resources for testing your project to ensure it runs on all of our supported products. Will you accept if we submit binaries for 32 bit systems? And may we know how to get those binaries in the final releases of this package?

**Comment by adonespitogo** [comment]
Today I will also be testing other boards and see if it compiles. These boards in particular are:

- OPI One
- OPI One Plus
- OPI PC
- OPI Zero

We have many more boards like Nano Pi, Tinker Board, Late Panda etc. to test but these are my priorities for today.

**Comment by uNetworkingAB** [comment]
Obviously I cannot accept binaries from third party as that would open for supply chain attack of the year 😉 If they work, they work, but I don't have resources to support edge case hardware (at some point someone will want to run uws on an 8 bit heart rate monitor) so you could just upload your binaries to your own repo and instqll from there. 👍

**Comment by adonespitogo** [comment]
Fair enough. Right now I'm trying to create my own package which contains the 32 bit binaries. I'm fiddling with the github workflows and so far I'm able to build binaries for `armv6` and `armv7`. I'm just wondering how you build the nodejs package since there's no package.json in the repo. Do you have other scripts for deploying the release of this package?

**Comment by adonespitogo** [comment]
Oh now I see, it's all in the `binaries` branch.

**Pull request merged**
