### PR TITLE
Add FreeBSD make target

### PR DESCRIPTION
**Pull request by swegen**
Requires [uNetworking/uSockets#36](https://github.com/uNetworking/uSockets/pull/36) to build.

### CODE REVIEW

**Comment by swegen** [comment]
Requires https://github.com/uNetworking/uSockets/pull/36 to build.

**Comment by alexhultman** [comment]
Very minimal change to support FreeBSD 👍

**Comment by alvar-freude** [comment]
Hi. Sorry, I don't really know much about node and yarn. The current version of uWebSockets.js doesn't seem to support FreeBSD as no binaries are included. How can I compile them? It shouldn't be too hard (if you know how ;-) ). www/uwebsockets port is installed. 
Thanks!

**Comment by alexhultman** [comment]
FreeBSD is not supported - you have to make it work on your own and maybe PR the changes needed. Sources does compile but I don't think the Node.js wrapper will compile on FreeBSD without small changes.

**Pull request merged**
