### PR TITLE
Fast Path - update json/body parser example

### PR DESCRIPTION
**Pull request by coder456**
_**Includes Fastest Path Possible**_

update the json body parse example with better generic `readBody` helper function, use tabs not spaces, simplify code

```
/* Simple example for reading Post body and parsing Json */

const uWS = require('../dist/uws.js');
const port = 9001;
const app = uWS.App().post('/json', (res, req) => {

	/* onAborted needs to be set if doing anything async like reading body */
	res.onAborted(() => res.aborted = true);

	/* read the request body */
	readBody(res, body => {

		/* get body text as string */
		console.log('body text:', body.toString());

		/* parse json */
		try { var obj = JSON.parse(body); }
		catch(e) { console.log('json parse error'); }
		console.log('json object:', obj);

		/* if response was aborted can't use it */
		if (res.aborted) return;

		/* respond to request */
		if (!obj) return res.writeStatus('400').end('invalid json');
		res.end('success');
	});
}).listen(port, token => token && console.log('Listening to port ' + port));

/* Helper function for reading body */
function readBody(res, cb) {
	let body;
	res.onData((arrayBuffer, isLast) => {
		const chunk = Buffer.from(arrayBuffer);
		body = body ? Buffer.concat([body, chunk]) : isLast ? chunk : Buffer.concat([chunk]);
		if (isLast) cb(body);
	});
}
```

### CODE REVIEW

**Comment by alexhultman** [comment]
This example has an entirely alien style. Tabs, comments, branches, not a single thing match the current style. It's convoluted and overly compact.

**Comment by coder456** [comment]
Feel free to change the style, but the examples need a simple readBody function that can be re-used etc not just an over complicated readJson function

**Comment by coder456** [comment]
Lol ok

**Comment by coder456** [comment]
This is how JavaScript is supposed to be written, you don't seem interested in the success of your own library if you dont make available a simple readBody function

**Comment by coder456** [comment]
I code javascript full time for many years get paid well for my job, I am assuming you dont have much javascript experience, who codes with spaces for indentation? strange stuff, this is supposed to be as simple as possible

**Comment by alexhultman** [comment]
Indeed

**Comment by claudiobonifazi** [comment]
Dude chill, a lot of people indent with spaces. I personally prefer tabs but to each their own. If you're that good you should find it easy to match the style guidelines of an existing project

**Pull request closed without merging**
